# Generated by Django 6.1.1 on 2026-09-15 02:45

import apps.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0001_initial'),
        ('positions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Used in URLs. It does not replace authorization.', unique=True, verbose_name='public ID')),
                ('contract_type', models.CharField(choices=[('INDEFINITE', 'Indefinite term'), ('FIXED_TERM', 'Fixed term'), ('TEMPORARY', 'Temporary'), ('INTERNSHIP', 'Internship')], max_length=20, verbose_name='contract type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='Required for fixed-term contracts; empty for indefinite ones.', null=True, verbose_name='end date')),
                ('probation_end_date', models.DateField(blank=True, null=True, verbose_name='end of probation')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20, verbose_name='status')),
                ('termination_reason', models.CharField(blank=True, choices=[('RESIGNATION', 'Resignation'), ('DISMISSAL_WITH_CAUSE', 'Dismissal with just cause'), ('DISMISSAL_WITHOUT_CAUSE', 'Dismissal without just cause'), ('MUTUAL_AGREEMENT', 'Mutual agreement'), ('CONTRACT_EXPIRY', 'End of fixed term'), ('RETIREMENT', 'Retirement'), ('DEATH', 'Death')], default='', max_length=40, verbose_name='termination reason')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='termination date')),
                ('signed_on', models.DateField(blank=True, null=True, verbose_name='signed on')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.company', verbose_name='employer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='employees.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'employment contract',
                'verbose_name_plural': 'employment contracts',
                'ordering': ('-start_date',),
                'permissions': [('terminate_contract', 'Can terminate employment contracts')],
            },
        ),
        migrations.CreateModel(
            name='ContractSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(default='GTQ', max_length=3, validators=[apps.core.validators.validate_currency_code], verbose_name='currency')),
                ('pay_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIWEEKLY', 'Twice a month'), ('WEEKLY', 'Weekly')], default='MONTHLY', max_length=20, verbose_name='pay frequency')),
                ('effective_from', models.DateField(verbose_name='effective from')),
                ('effective_to', models.DateField(blank=True, help_text='Empty means current salary.', null=True, verbose_name='effective to')),
                ('change_reason', models.CharField(choices=[('INITIAL', 'Initial salary'), ('MERIT_INCREASE', 'Merit increase'), ('PROMOTION', 'Promotion'), ('ADJUSTMENT', 'Adjustment or correction'), ('LEGAL_MINIMUM', 'Legal minimum wage update'), ('DEMOTION', 'Demotion')], max_length=40, verbose_name='reason')),
                ('justification', models.CharField(blank=True, help_text='Required when the amount is outside the salary band of the position.', max_length=300, verbose_name='justification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registered by')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='contracts.employmentcontract', verbose_name='contract')),
            ],
            options={
                'verbose_name': 'contract salary',
                'verbose_name_plural': 'contract salaries',
                'ordering': ('-effective_from',),
                'permissions': [('view_salary', 'Can view salary amounts'), ('change_salary', 'Can register salary changes')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='Empty means current assignment.', null=True, verbose_name='end date')),
                ('is_primary', models.BooleanField(default=True, verbose_name='primary assignment')),
                ('fte', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='1.00 is full time.', max_digits=3, verbose_name='full-time equivalent')),
                ('assignment_reason', models.CharField(choices=[('INITIAL', 'Initial assignment'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer'), ('REORGANIZATION', 'Reorganization'), ('TEMPORARY_COVER', 'Temporary cover')], default='INITIAL', max_length=40, verbose_name='reason')),
                ('position', models.ForeignKey(help_text='The department is derived from the position.', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='positions.position', verbose_name='position')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='contracts.employmentcontract', verbose_name='contract')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
                'ordering': ('-start_date',),
            },
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['employee', 'status'], name='contract_employee_status_idx'),
        ),
        migrations.AddIndex(
            model_name='employmentcontract',
            index=models.Index(fields=['status', 'end_date'], name='contract_status_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['ACTIVE', 'SUSPENDED'])), fields=('employee',), name='uniq_live_contract_per_employee', violation_error_message='That employee already has a live contract.'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='contract_end_after_start', violation_error_message='The end date cannot precede the start date.'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract_type', 'FIXED_TERM'), _negated=True), ('end_date__isnull', False), _connector='OR'), name='contract_fixed_term_has_end', violation_error_message='A fixed-term contract needs an end date.'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract_type', 'INDEFINITE'), _negated=True), ('end_date__isnull', True), _connector='OR'), name='contract_indefinite_has_no_end', violation_error_message='An indefinite contract cannot have an end date.'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('probation_end_date__isnull', True), ('probation_end_date__gte', models.F('start_date')), _connector='OR'), name='contract_probation_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('start_date')), _connector='OR'), name='contract_termination_after_start'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'TERMINATED'), ('termination_date__isnull', False), models.Q(('termination_reason', ''), _negated=True)), models.Q(models.Q(('status', 'TERMINATED'), _negated=True), ('termination_date__isnull', True), ('termination_reason', '')), _connector='OR'), name='contract_termination_is_consistent', violation_error_message='A terminated contract needs a date and a reason, and only a terminated one.'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'SUSPENDED', 'TERMINATED', 'EXPIRED'])), name='contract_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('contract_type__in', ['INDEFINITE', 'FIXED_TERM', 'TEMPORARY', 'INTERNSHIP'])), name='contract_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.CheckConstraint(condition=models.Q(('termination_reason', ''), ('termination_reason__in', ['RESIGNATION', 'DISMISSAL_WITH_CAUSE', 'DISMISSAL_WITHOUT_CAUSE', 'MUTUAL_AGREEMENT', 'CONTRACT_EXPIRY', 'RETIREMENT', 'DEATH']), _connector='OR'), name='contract_termination_reason_valid'),
        ),
        migrations.AddIndex(
            model_name='contractsalary',
            index=models.Index(fields=['contract', '-effective_from'], name='salary_contract_from_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractsalary',
            constraint=models.UniqueConstraint(fields=('contract', 'effective_from'), name='uniq_salary_per_contract_and_start', violation_error_message='There is already a salary starting on that date.'),
        ),
        migrations.AddConstraint(
            model_name='contractsalary',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('contract',), name='uniq_open_salary_per_contract', violation_error_message='That contract already has a current salary.'),
        ),
        migrations.AddConstraint(
            model_name='contractsalary',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_amount_positive', violation_error_message='The salary must be greater than zero.'),
        ),
        migrations.AddConstraint(
            model_name='contractsalary',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='salary_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='contractsalary',
            constraint=models.CheckConstraint(condition=models.Q(('pay_frequency__in', ['MONTHLY', 'BIWEEKLY', 'WEEKLY'])), name='salary_pay_frequency_valid'),
        ),
        migrations.AddConstraint(
            model_name='contractsalary',
            constraint=models.CheckConstraint(condition=models.Q(('change_reason__in', ['INITIAL', 'MERIT_INCREASE', 'PROMOTION', 'ADJUSTMENT', 'LEGAL_MINIMUM', 'DEMOTION'])), name='salary_change_reason_valid'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['contract', 'end_date'], name='assignment_contract_end_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['position', 'end_date'], name='assignment_position_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('contract', 'position', 'start_date'), name='uniq_assignment'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('end_date__isnull', True), ('is_primary', True)), fields=('contract',), name='uniq_open_primary_assignment', violation_error_message='That contract already has a current primary assignment.'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='assignment_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('fte__gt', 0), ('fte__lte', Decimal('1.00'))), name='assignment_fte_in_range', violation_error_message='The FTE must be greater than 0 and at most 1.'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('assignment_reason__in', ['INITIAL', 'PROMOTION', 'TRANSFER', 'REORGANIZATION', 'TEMPORARY_COVER'])), name='assignment_reason_valid'),
        ),
    ]
