# Generated by Django 6.1.1 on 2026-09-11 23:20

import apps.accounts.managers
import apps.core.constants
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(error_messages={'unique': 'An account with that email address already exists.'}, help_text='Used as the login identifier. Stored in lowercase.', max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting, so the audit trail survives.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Grants access to the Django admin. Reserved for SUPERADMIN.', verbose_name='staff status')),
                ('must_change_password', models.BooleanField(default=False, help_text='Forces a password change on the next sign-in.', verbose_name='must change password')),
                ('language', models.CharField(choices=apps.core.constants.language_choices, default=apps.core.constants.default_language, help_text='Interface language. Follows the person across devices.', max_length=10, verbose_name='preferred language')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('email',),
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
