# Generated by Django 6.1.1 on 2026-09-12 01:34

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='For example G05.', max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('level', models.PositiveSmallIntegerField(help_text='Hierarchical order; higher means more senior.', verbose_name='level')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='minimum salary')),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='maximum salary')),
                ('currency', models.CharField(default='GTQ', help_text='ISO 4217 code.', max_length=3, validators=[apps.core.validators.validate_currency_code], verbose_name='currency')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'job grade',
                'verbose_name_plural': 'job grades',
                'ordering': ('level', 'code'),
                'constraints': [models.CheckConstraint(condition=models.Q(('min_salary__gt', 0)), name='jobgrade_min_salary_positive', violation_error_message='The minimum salary must be greater than zero.'), models.CheckConstraint(condition=models.Q(('max_salary__gte', models.F('min_salary'))), name='jobgrade_range_is_ordered', violation_error_message='The maximum salary cannot be lower than the minimum salary.'), models.CheckConstraint(condition=models.Q(('level__gte', 1)), name='jobgrade_level_positive')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='Unique across the whole organization.', max_length=20, unique=True, verbose_name='code')),
                ('title', models.CharField(help_text='Unique within the department.', max_length=120, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Role profile. Specific to this department.', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('department', models.ForeignKey(help_text='The area this position belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='departments.department', verbose_name='department')),
                ('job_grade', models.ForeignKey(help_text='Determines the salary band. It is not stored here.', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='positions.jobgrade', verbose_name='job grade')),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'positions',
                'ordering': ('department__name', 'title'),
                'indexes': [models.Index(fields=['department', 'is_active'], name='position_dept_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'title'), name='uniq_position_title_per_department', violation_error_message='That department already has a position with this title.')],
            },
        ),
    ]
