# Generated by Django 6.1.1 on 2026-09-12 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='Unique within the company.', max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('cost_center', models.CharField(blank=True, help_text='Link with accounting.', max_length=30, verbose_name='cost center')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate instead of deleting: the history refers to it.', verbose_name='active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='core.company', verbose_name='company')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave empty for the root of the organization chart.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='departments.department', verbose_name='parent department')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['parent'], name='department_parent_idx'), models.Index(fields=['company', 'is_active'], name='department_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_department_code_per_company', violation_error_message='That company already has a department with this code.'), models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='department_is_not_its_own_parent', violation_error_message='A department cannot be its own parent.')],
            },
        ),
    ]
