# Generated by Django 6.1.1 on 2026-09-12 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHeadship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='Empty means currently in charge.', null=True, verbose_name='end date')),
                ('appointment_note', models.CharField(blank=True, max_length=200, verbose_name='appointment note')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headships', to='departments.department', verbose_name='department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='headships', to='employees.employee', verbose_name='head')),
            ],
            options={
                'verbose_name': 'department headship',
                'verbose_name_plural': 'department headships',
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['employee', 'end_date'], name='headship_employee_idx')],
                'constraints': [models.UniqueConstraint(fields=('department', 'start_date'), name='uniq_headship_per_department_and_start'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('department',), name='uniq_current_head_per_department', violation_error_message='That department already has a current head.'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='headship_dates_ordered', violation_error_message='The end date cannot precede the start date.')],
            },
        ),
    ]
