"""Generación del PDF de un reporte, con QR y marca de agua de trazabilidad.

Dos decisiones que conviene tener a la vista:

- **El QR apunta al sistema, no al archivo.** Abre el mismo reporte con los
  mismos filtros y **exige iniciar sesión**. No lleva token ni enlace firmado:
  cualquier token sería una credencial más débil que la sesión que ya pedimos,
  y un QR fotografiado no debe abrir datos de nadie.
- **Cada página lleva quién lo generó, cuándo y con qué filtros.** Un PDF que
  se reenvía por correo sale del sistema para siempre; la marca de agua hace
  que siga diciendo de dónde vino.

Solo formato: ninguna regla de negocio ni de autorización vive aquí (regla 3).
"""

from __future__ import annotations

from io import BytesIO

from django.utils.translation import gettext as _
from reportlab.graphics.barcode import qr
from reportlab.graphics.shapes import Drawing
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from apps.reports.builders import ReportResult
from apps.reports.constants import PDF_ROW_LIMIT

#: Jade de la marca (docs/ux/16-identidad-de-marca.md).
JADE = colors.HexColor("#0F6E5C")
JADE_LIGHT = colors.HexColor("#E8F4F1")

#: Lado del QR impreso.
QR_SIZE = 22 * mm


def build_pdf(
    *,
    title: str,
    result: ReportResult,
    filters_text: str,
    generated_by: str,
    generated_at: str,
    report_url: str,
) -> tuple[bytes, bool]:
    """Devuelve el PDF y si hubo que recortar filas."""
    stream = BytesIO()
    document = SimpleDocTemplate(
        stream,
        pagesize=landscape(A4),
        topMargin=18 * mm,
        bottomMargin=26 * mm,  # espacio para la marca de agua y el QR
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        title=title,
        author=generated_by,
        subject=filters_text,
    )

    styles = getSampleStyleSheet()
    heading = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=16, alignment=0, textColor=JADE
    )
    meta = ParagraphStyle("ReportMeta", parent=styles["Normal"], fontSize=9, textColor=colors.grey)
    cell = ParagraphStyle("ReportCell", parent=styles["Normal"], fontSize=8, leading=10)

    rows = result.rows[:PDF_ROW_LIMIT]
    truncated = len(result.rows) > PDF_ROW_LIMIT

    story = [
        Paragraph(_text(title), heading),
        Paragraph(_text(filters_text), meta),
        Spacer(1, 6 * mm),
        _table(result, rows, cell),
    ]
    if truncated:
        story += [
            Spacer(1, 4 * mm),
            Paragraph(
                _("Only the first %(shown)s rows are shown. Export to Excel to see them all.")
                % {"shown": PDF_ROW_LIMIT},
                meta,
            ),
        ]

    footer = _footer_painter(generated_by=generated_by, generated_at=generated_at, url=report_url)
    document.build(story, onFirstPage=footer, onLaterPages=footer)
    return stream.getvalue(), truncated


def _table(result: ReportResult, rows: list[dict], cell_style: ParagraphStyle) -> Table:
    header = [Paragraph(f"<b>{column.label}</b>", cell_style) for column in result.columns]
    body = [
        [Paragraph(_text(row.get(column.key)), cell_style) for column in result.columns]
        for row in rows
    ]
    data = [header, *body]

    if result.totals:
        data.append(
            [
                Paragraph(f"<b>{_text(result.totals.get(column.key, ''))}</b>", cell_style)
                for column in result.columns
            ]
        )

    table = Table(data, repeatRows=1, hAlign="LEFT")
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), JADE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D6DEDB")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2 if result.totals else -1), [colors.white, JADE_LIGHT]),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
    if result.totals:
        style.append(("BACKGROUND", (0, -1), (-1, -1), JADE_LIGHT))
    table.setStyle(TableStyle(style))
    return table


def _footer_painter(*, generated_by: str, generated_at: str, url: str):
    """Pinta la marca de agua y el QR en cada página."""

    def paint(canvas, document) -> None:
        canvas.saveState()
        width, _height = document.pagesize

        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.grey)
        trace = _("Generated by %(actor)s on %(moment)s") % {
            "actor": generated_by,
            "moment": generated_at,
        }
        canvas.drawString(12 * mm, 14 * mm, trace)
        canvas.drawString(
            12 * mm,
            10 * mm,
            _("Internal document: it contains personal data of the organisation."),
        )
        canvas.drawRightString(
            width - 40 * mm, 10 * mm, _("Page %(number)s") % {"number": canvas.getPageNumber()}
        )

        widget = qr.QrCodeWidget(url)
        bounds = widget.getBounds()
        drawing = Drawing(
            QR_SIZE,
            QR_SIZE,
            transform=[
                QR_SIZE / (bounds[2] - bounds[0]),
                0,
                0,
                QR_SIZE / (bounds[3] - bounds[1]),
                0,
                0,
            ],
        )
        drawing.add(widget)
        drawing.drawOn(canvas, width - 34 * mm, 8 * mm)
        canvas.restoreState()

    return paint


def _text(value) -> str:
    """Todo a texto, escapando el marcado que ReportLab interpretaría.

    No es cosmético: un párrafo admite etiquetas como `<img src="...">`, y
    ReportLab **carga** ese recurso al construir el PDF. Sin escapar, un nombre
    de departamento podría hacer que el servidor pida una dirección interna, o
    incrustar enlaces ajenos en un documento que circula fuera
    (docs/security/revision-reportes.md, H-2).
    """
    if value is None or value == "":
        return "—"
    return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
