# Generated by Django 6.1.1 on 2026-09-11 23:20

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(help_text='Short internal identifier, e.g. HQ.', max_length=20, unique=True, verbose_name='code')),
                ('legal_name', models.CharField(max_length=200, verbose_name='legal name')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='trade name')),
                ('tax_id', models.CharField(help_text='Employer tax identification number.', max_length=20, unique=True, verbose_name='tax ID')),
                ('country', models.CharField(default='GT', help_text='ISO 3166-1 alpha-2 code.', max_length=2, validators=[apps.core.validators.validate_country_code], verbose_name='country')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='date')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether it is mandated by law rather than granted by the company.', verbose_name='statutory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holidays', to='core.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holidays',
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='uniq_holiday_per_company_and_date', violation_error_message='This company already has a holiday on that date.')],
            },
        ),
    ]
