# Generated by Django 6.1.1 on 2026-09-19 22:49

import apps.documents.models
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Only HR administration and auditing can open its content.', verbose_name='confidential')),
                ('requires_expiry', models.BooleanField(default=False, help_text='For example, a medical certificate or a work permit.', verbose_name='requires expiry date')),
                ('employee_can_upload', models.BooleanField(default=False, help_text='Types a person may add to their own file, such as a diploma.', verbose_name='the employee can upload it')),
                ('retention_years', models.PositiveSmallIntegerField(default=0, help_text='How long it must be kept. 0 means no policy defined yet.', verbose_name='retention (years)')),
                ('allowed_extensions', models.CharField(default='pdf', help_text='Comma-separated list, for example: pdf,png,jpg', max_length=100, verbose_name='allowed formats')),
                ('max_size_mb', models.PositiveSmallIntegerField(default=10, verbose_name='maximum size (MB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'document type',
                'verbose_name_plural': 'document types',
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('max_size_mb__gt', 0), ('max_size_mb__lte', 25)), name='document_type_size_in_range', violation_error_message='The maximum size must be between 1 and 25 MB.'), models.CheckConstraint(condition=models.Q(('retention_years__lte', 50)), name='document_type_retention_in_range', violation_error_message='The retention cannot exceed 50 years.')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='public id')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('stored_path', models.FileField(max_length=300, upload_to=apps.documents.models.document_upload_path, verbose_name='stored file')),
                ('original_filename', models.CharField(max_length=255, verbose_name='original file name')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='declared content type')),
                ('size_bytes', models.PositiveIntegerField(verbose_name='size (bytes)')),
                ('checksum_sha256', models.CharField(max_length=64, verbose_name='checksum (SHA-256)')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='issued on')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='expires on')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('archived_reason', models.CharField(blank=True, max_length=300, verbose_name='archiving reason')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype', verbose_name='document type')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='employees.employee', verbose_name='employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'employee document',
                'verbose_name_plural': 'employee documents',
                'ordering': ('-created_at',),
                'permissions': [('view_sensitive_document', 'Can open confidential documents'), ('archive_document', 'Can archive a document')],
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['employee', 'document_type'], name='document_employee_type_idx'), models.Index(fields=['expires_on'], name='document_expires_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employee', 'document_type', 'checksum_sha256'), name='uniq_active_document_per_checksum', violation_error_message='That same file is already in the file.'), models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0)), name='document_size_positive', violation_error_message='An empty file explains nothing.'), models.CheckConstraint(condition=django.db.models.lookups.Exact(django.db.models.functions.text.Length('checksum_sha256'), 64), name='document_checksum_is_sha256'), models.CheckConstraint(condition=models.Q(('issued_on__isnull', True), ('expires_on__isnull', True), ('issued_on__lte', models.F('expires_on')), _connector='OR'), name='document_dates_ordered', violation_error_message='The expiry cannot precede the issue date.')],
            },
        ),
    ]
