# Generated by Django 6.1.1 on 2026-09-18 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('granted_days', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='granted days')),
                ('source', models.CharField(choices=[('ACCRUAL', 'Monthly accrual'), ('MANUAL', 'Granted by HR'), ('CARRYOVER', 'Carried over')], default='ACCRUAL', max_length=10, verbose_name='source')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_entitlements', to='employees.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'leave entitlement',
                'verbose_name_plural': 'leave entitlements',
                'ordering': ('-period_start',),
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('is_paid', models.BooleanField(default=True, verbose_name='paid')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='requires approval')),
                ('requires_document', models.BooleanField(default=False, help_text='For example, a medical certificate.', verbose_name='requires document')),
                ('allows_negative_balance', models.BooleanField(default=False, help_text='Only for types the company grants in advance.', verbose_name='allows negative balance')),
                ('default_annual_days', models.DecimalField(decimal_places=2, default=0, help_text='Days accrued per year. They are granted month by month.', max_digits=5, verbose_name='annual days')),
                ('min_notice_days', models.PositiveSmallIntegerField(default=0, verbose_name='minimum notice (days)')),
                ('is_sensitive', models.BooleanField(default=False, help_text='The team calendar shows it as a generic absence, without the type.', verbose_name='sensitive')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'leave type',
                'verbose_name_plural': 'leave types',
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('default_annual_days__gte', 0), ('default_annual_days__lte', 60)), name='leave_type_annual_days_in_range', violation_error_message='The annual days must be between 0 and 60.')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Used in URLs. It does not replace authorization.', unique=True, verbose_name='public ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('working_days', models.DecimalField(decimal_places=2, help_text='Calculated from the schedule and the public holidays.', max_digits=5, verbose_name='working days')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10, verbose_name='status')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='reason')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decided at')),
                ('decision_note', models.CharField(blank=True, max_length=300, verbose_name='decision note')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='employees.employee', verbose_name='employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='leave.leavetype', verbose_name='leave type')),
            ],
            options={
                'verbose_name': 'leave request',
                'verbose_name_plural': 'leave requests',
                'ordering': ('-start_date',),
                'permissions': [('approve_leave', 'Can approve or reject leave requests')],
            },
        ),
        migrations.CreateModel(
            name='LeaveLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('entry_type', models.CharField(choices=[('ACCRUAL', 'Accrual'), ('CONSUMPTION', 'Consumption'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], max_length=12, verbose_name='type')),
                ('days', models.DecimalField(decimal_places=2, help_text='Positive adds to the balance; negative consumes it.', max_digits=6, verbose_name='days')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_ledger', to='employees.employee', verbose_name='employee')),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leaveentitlement', verbose_name='entitlement')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leaverequest', verbose_name='leave request')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='leave.leavetype', verbose_name='leave type')),
            ],
            options={
                'verbose_name': 'leave ledger entry',
                'verbose_name_plural': 'leave ledger entries',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'view'),
            },
        ),
        migrations.AddField(
            model_name='leaveentitlement',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='leave.leavetype', verbose_name='leave type'),
        ),
        migrations.CreateModel(
            name='LeaveRequestTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=10, verbose_name='from')),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=10, verbose_name='to')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='leave.leaverequest', verbose_name='leave request')),
            ],
            options={
                'verbose_name': 'leave request transition',
                'verbose_name_plural': 'leave request transitions',
                'ordering': ('-created_at',),
                'default_permissions': ('add', 'view'),
                'constraints': [models.CheckConstraint(condition=models.Q(('from_status__in', ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED']), ('to_status__in', ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED'])), name='transition_statuses_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['employee', 'start_date'], name='leave_employee_start_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='leave_status_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='leave_dates_ordered', violation_error_message='The end date cannot precede the start date.'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('working_days__gt', 0)), name='leave_working_days_positive', violation_error_message='The request must cover at least one working day.'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED'])), name='leave_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPROVED', 'REJECTED']), ('decided_at__isnull', False)), models.Q(models.Q(('status__in', ['APPROVED', 'REJECTED']), _negated=True), ('decided_at__isnull', True)), _connector='OR'), name='leave_decision_is_consistent', violation_error_message='A decided request needs the date it was decided.'),
        ),
        migrations.AddIndex(
            model_name='leaveledgerentry',
            index=models.Index(fields=['employee', 'leave_type'], name='ledger_employee_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaveledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('days', 0), _negated=True), name='ledger_days_not_zero', violation_error_message='An entry of zero days explains nothing.'),
        ),
        migrations.AddConstraint(
            model_name='leaveledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['ACCRUAL', 'CONSUMPTION', 'REVERSAL', 'ADJUSTMENT'])), name='ledger_entry_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='leaveledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entry_type__in', ['CONSUMPTION', 'REVERSAL']), _negated=True), ('request__isnull', False), _connector='OR'), name='ledger_movement_has_its_request', violation_error_message='A consumption or reversal needs its request.'),
        ),
        migrations.AddConstraint(
            model_name='leaveentitlement',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'period_start'), name='uniq_entitlement_per_period', violation_error_message='That period was already accrued.'),
        ),
        migrations.AddConstraint(
            model_name='leaveentitlement',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lt', models.F('period_end'))), name='entitlement_period_ordered', violation_error_message='The period start must precede its end.'),
        ),
        migrations.AddConstraint(
            model_name='leaveentitlement',
            constraint=models.CheckConstraint(condition=models.Q(('granted_days__gte', 0)), name='entitlement_days_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='leaveentitlement',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['ACCRUAL', 'MANUAL', 'CARRYOVER'])), name='entitlement_source_valid'),
        ),
    ]
