# Generated by Django 6.1.1 on 2026-09-19 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leave', '0001_leave_phase6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaverequest',
            name='leave_decision_is_consistent',
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['APPROVED', 'REJECTED']), ('decided_at__isnull', False)), models.Q(('status__in', ['DRAFT', 'SUBMITTED']), ('decided_at__isnull', True)), ('status', 'CANCELLED'), _connector='OR'), name='leave_decision_is_consistent', violation_error_message='A decided request needs the date it was decided.'),
        ),
    ]
