# Generated by Django 6.1.1 on 2026-09-19 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leave', '0002_cancelled_keeps_its_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaverequesttransition',
            name='transition_statuses_valid',
        ),
        migrations.AlterField(
            model_name='leaverequesttransition',
            name='from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Pending approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=10, verbose_name='from'),
        ),
        migrations.AddConstraint(
            model_name='leaveledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('days__gt', 0), ('entry_type__in', ['ACCRUAL', 'REVERSAL'])), models.Q(('days__lt', 0), ('entry_type', 'CONSUMPTION')), ('entry_type', 'ADJUSTMENT'), _connector='OR'), name='ledger_sign_matches_type', violation_error_message='The sign of the days does not match the entry type.'),
        ),
        migrations.AddConstraint(
            model_name='leaverequesttransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status__in', ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', '']), ('to_status__in', ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED'])), name='transition_statuses_valid'),
        ),
        migrations.AddConstraint(
            model_name='leaverequesttransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='transition_changes_status'),
        ),
    ]
