# Generated by Django 6.1.1 on 2026-09-19 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_design_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAccrualTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('min_years_of_service', models.PositiveSmallIntegerField(help_text='Completed years of service from which this tier applies.', verbose_name='from years of service')),
                ('annual_days', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='days per year')),
            ],
            options={
                'verbose_name': 'accrual tier',
                'verbose_name_plural': 'accrual tiers',
                'ordering': ('leave_type', 'min_years_of_service'),
            },
        ),
        migrations.AddField(
            model_name='leavetype',
            name='max_backdating_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many days after it started the leave can still be registered. 0 means it must be requested in advance.', verbose_name='retroactive registration (days)'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.CheckConstraint(condition=models.Q(('max_backdating_days__lte', 30)), name='leave_type_backdating_in_range', violation_error_message='Retroactive registration cannot exceed 30 days.'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.CheckConstraint(condition=models.Q(('min_notice_days', 0), ('max_backdating_days', 0), _connector='OR'), name='leave_type_notice_or_backdating', violation_error_message='A type cannot require notice and also allow retroactive registration.'),
        ),
        migrations.AddField(
            model_name='leaveaccrualtier',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accrual_tiers', to='leave.leavetype', verbose_name='leave type'),
        ),
        migrations.AddConstraint(
            model_name='leaveaccrualtier',
            constraint=models.UniqueConstraint(fields=('leave_type', 'min_years_of_service'), name='uniq_tier_per_type_and_seniority', violation_error_message='That type already has a tier for those years.'),
        ),
        migrations.AddConstraint(
            model_name='leaveaccrualtier',
            constraint=models.CheckConstraint(condition=models.Q(('min_years_of_service__gte', 1)), name='tier_starts_after_first_year', violation_error_message='A tier starts at one year of service or more.'),
        ),
        migrations.AddConstraint(
            model_name='leaveaccrualtier',
            constraint=models.CheckConstraint(condition=models.Q(('annual_days__gte', 0), ('annual_days__lte', 60)), name='tier_annual_days_in_range', violation_error_message='The annual days must be between 0 and 60.'),
        ),
    ]
