# Generated by Django 6.1.1 on 2026-09-18 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('weekly_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='weekly hours')),
                ('grace_minutes', models.PositiveSmallIntegerField(default=10, help_text='Minutes of tolerance before an arrival counts as late.', verbose_name='grace period (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'work schedule',
                'verbose_name_plural': 'work schedules',
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('weekly_hours__gt', 0), ('weekly_hours__lte', 168)), name='schedule_weekly_hours_in_range', violation_error_message='The weekly hours must be between 0 and 168.'), models.CheckConstraint(condition=models.Q(('grace_minutes__lte', 120)), name='schedule_grace_in_range', violation_error_message='The grace period cannot exceed 120 minutes.')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('work_date', models.DateField(verbose_name='work date')),
                ('check_in_at', models.DateTimeField(verbose_name='check in')),
                ('check_out_at', models.DateTimeField(blank=True, null=True, verbose_name='check out')),
                ('source', models.CharField(choices=[('SELF', 'Self-service'), ('SUPERVISOR', 'Registered by the manager'), ('HR', 'Registered by HR'), ('DEVICE', 'Time clock'), ('IMPORT', 'Imported')], default='SELF', max_length=12, verbose_name='source')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='employees.employee', verbose_name='employee')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registered by')),
            ],
            options={
                'verbose_name': 'attendance entry',
                'verbose_name_plural': 'attendance entries',
                'ordering': ('-work_date', '-check_in_at'),
                'permissions': [('adjust_attendance', 'Can correct attendance entries')],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='entry_employee_date_idx'), models.Index(fields=['work_date'], name='entry_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date', 'check_in_at'), name='uniq_entry_per_employee_and_check_in'), models.UniqueConstraint(condition=models.Q(('check_out_at__isnull', True)), fields=('employee',), name='uniq_open_entry_per_employee', violation_error_message='That person already has an open entry.'), models.CheckConstraint(condition=models.Q(('check_out_at__isnull', True), ('check_in_at__lt', models.F('check_out_at')), _connector='OR'), name='entry_times_ordered', violation_error_message='The check-out must come after the check-in (RN-50).'), models.CheckConstraint(condition=models.Q(('source__in', ['SELF', 'SUPERVISOR', 'HR', 'DEVICE', 'IMPORT'])), name='entry_source_valid')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('work_date', models.DateField(verbose_name='work date')),
                ('incident_type', models.CharField(choices=[('LATE', 'Late arrival'), ('EARLY_LEAVE', 'Early leave'), ('ABSENCE', 'Absence'), ('OVERTIME', 'Overtime'), ('MISSING_PUNCH', 'Missing punch')], max_length=16, verbose_name='type')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='minutes')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('JUSTIFIED', 'Justified'), ('REJECTED', 'Rejected')], default='OPEN', max_length=10, verbose_name='status')),
                ('justification', models.CharField(blank=True, max_length=300, verbose_name='justification')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_incidents', to='employees.employee', verbose_name='employee')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
            ],
            options={
                'verbose_name': 'attendance incident',
                'verbose_name_plural': 'attendance incidents',
                'ordering': ('-work_date', 'incident_type'),
                'indexes': [models.Index(fields=['employee', 'work_date'], name='incident_employee_date_idx'), models.Index(fields=['status', 'work_date'], name='incident_status_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date', 'incident_type'), name='uniq_incident_per_employee_date_and_type'), models.CheckConstraint(condition=models.Q(('incident_type__in', ['LATE', 'EARLY_LEAVE', 'ABSENCE', 'OVERTIME', 'MISSING_PUNCH'])), name='incident_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['OPEN', 'JUSTIFIED', 'REJECTED'])), name='incident_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', True), ('status', 'OPEN')), models.Q(models.Q(('status', 'OPEN'), _negated=True), ('resolved_at__isnull', False)), _connector='OR'), name='incident_resolution_is_consistent', violation_error_message='A resolved incident needs the date it was resolved.')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='Empty means current schedule.', null=True, verbose_name='end date')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='contracts.employmentcontract', verbose_name='contract')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.workschedule', verbose_name='work schedule')),
            ],
            options={
                'verbose_name': 'schedule assignment',
                'verbose_name_plural': 'schedule assignments',
                'ordering': ('-start_date',),
                'constraints': [models.UniqueConstraint(fields=('contract', 'start_date'), name='uniq_schedule_per_contract_and_start'), models.UniqueConstraint(condition=models.Q(('end_date__isnull', True)), fields=('contract',), name='uniq_open_schedule_per_contract', violation_error_message='That contract already has a current schedule.'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='schedule_assignment_period_ordered', violation_error_message='The end date cannot precede the start date.')],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='break (minutes)')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='attendance.workschedule', verbose_name='work schedule')),
            ],
            options={
                'verbose_name': 'work schedule day',
                'verbose_name_plural': 'work schedule days',
                'ordering': ('work_schedule', 'weekday'),
                'constraints': [models.UniqueConstraint(fields=('work_schedule', 'weekday'), name='uniq_day_per_schedule', violation_error_message='That schedule already has this weekday.'), models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedule_day_times_ordered', violation_error_message='The start time must precede the end time.'), models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='schedule_day_weekday_valid')],
            },
        ),
    ]
