# Generated by Django 6.1.1 on 2026-09-11 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='occurred at')),
                ('actor_repr', models.CharField(help_text='Textual actor at the time of the event; survives account deletion.', max_length=150, verbose_name='actor (snapshot)')),
                ('action', models.CharField(choices=[('LOGIN', 'Sign in'), ('LOGIN_FAILED', 'Failed sign-in'), ('LOGOUT', 'Sign out'), ('PASSWORD_CHANGE', 'Password change'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_COMPLETE', 'Password reset completed'), ('EMAIL_VERIFIED', 'Email verified'), ('USER_CREATE', 'User created'), ('USER_DEACTIVATE', 'User deactivated'), ('ACTIVATION_CODE_ISSUE', 'Activation code issued'), ('ACTIVATION_CODE_REDEEM', 'Activation code redeemed'), ('ACTIVATION_CODE_FAILED', 'Activation code rejected'), ('ACTIVATION_CODE_REVOKE', 'Activation code revoked'), ('ROLE_CHANGE', 'Role changed'), ('PERMISSION_CHANGE', 'Permission changed'), ('PERMISSION_DENIED', 'Permission denied'), ('EMPLOYEE_CREATE', 'Employee created'), ('EMPLOYEE_UPDATE', 'Employee updated'), ('EMPLOYEE_VIEW_SENSITIVE', 'Sensitive employee data viewed'), ('CONTRACT_CREATE', 'Contract created'), ('CONTRACT_UPDATE', 'Contract updated'), ('CONTRACT_TERMINATE', 'Contract terminated'), ('SALARY_CHANGE', 'Salary changed'), ('ASSIGNMENT_CREATE', 'Assignment created'), ('ASSIGNMENT_END', 'Assignment ended'), ('LEAVE_SUBMIT', 'Leave request submitted'), ('LEAVE_APPROVE', 'Leave request approved'), ('LEAVE_REJECT', 'Leave request rejected'), ('LEAVE_CANCEL', 'Leave request cancelled'), ('ATTENDANCE_ADJUST', 'Attendance adjusted'), ('DOCUMENT_UPLOAD', 'Document uploaded'), ('DOCUMENT_DOWNLOAD', 'Document downloaded'), ('DOCUMENT_DELETE', 'Document deleted'), ('PAYROLL_RUN_EXECUTE', 'Payroll run executed'), ('PAYROLL_RUN_APPROVE', 'Payroll run approved'), ('EXPORT_DATA', 'Data exported')], max_length=40, verbose_name='action')),
                ('object_type', models.CharField(blank=True, help_text='Weak pointer in app_label.ModelName form. Not a foreign key.', max_length=60, verbose_name='object type')),
                ('object_id', models.CharField(blank=True, max_length=40, verbose_name='object ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='object (snapshot)')),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DENIED', 'Denied')], default='SUCCESS', max_length=10, verbose_name='outcome')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('request_id', models.UUIDField(blank=True, help_text='Correlates this event with the application logs.', null=True, verbose_name='request ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Filtered diff. Never contains credentials or personal identifiers.', verbose_name='metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the action was performed by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'audit event',
                'verbose_name_plural': 'audit events',
                'ordering': ('-occurred_at', '-id'),
                'permissions': [('view_audit_log', 'Can browse the audit log')],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['actor', '-occurred_at'], name='audit_actor_time_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_object_idx'), models.Index(fields=['action', '-occurred_at'], name='audit_action_time_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('outcome__in', ['SUCCESS', 'FAILURE', 'DENIED'])), name='audit_outcome_valid'), models.CheckConstraint(condition=models.Q(('action__in', ['LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETE', 'EMAIL_VERIFIED', 'USER_CREATE', 'USER_DEACTIVATE', 'ACTIVATION_CODE_ISSUE', 'ACTIVATION_CODE_REDEEM', 'ACTIVATION_CODE_FAILED', 'ACTIVATION_CODE_REVOKE', 'ROLE_CHANGE', 'PERMISSION_CHANGE', 'PERMISSION_DENIED', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_VIEW_SENSITIVE', 'CONTRACT_CREATE', 'CONTRACT_UPDATE', 'CONTRACT_TERMINATE', 'SALARY_CHANGE', 'ASSIGNMENT_CREATE', 'ASSIGNMENT_END', 'LEAVE_SUBMIT', 'LEAVE_APPROVE', 'LEAVE_REJECT', 'LEAVE_CANCEL', 'ATTENDANCE_ADJUST', 'DOCUMENT_UPLOAD', 'DOCUMENT_DOWNLOAD', 'DOCUMENT_DELETE', 'PAYROLL_RUN_EXECUTE', 'PAYROLL_RUN_APPROVE', 'EXPORT_DATA'])), name='audit_action_valid')],
            },
        ),
    ]
