# Generated by Django 6.1.1 on 2026-09-18 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_salary_view_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auditevent',
            name='audit_action_valid',
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Sign in'), ('LOGIN_FAILED', 'Failed sign-in'), ('LOGOUT', 'Sign out'), ('PASSWORD_CHANGE', 'Password change'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_COMPLETE', 'Password reset completed'), ('EMAIL_VERIFIED', 'Email verified'), ('USER_CREATE', 'User created'), ('USER_DEACTIVATE', 'User deactivated'), ('ACTIVATION_CODE_ISSUE', 'Activation code issued'), ('ACTIVATION_CODE_REDEEM', 'Activation code redeemed'), ('ACTIVATION_CODE_FAILED', 'Activation code rejected'), ('ACTIVATION_CODE_REVOKE', 'Activation code revoked'), ('ROLE_CHANGE', 'Role changed'), ('PERMISSION_CHANGE', 'Permission changed'), ('PERMISSION_DENIED', 'Permission denied'), ('DEPARTMENT_CREATE', 'Department created'), ('DEPARTMENT_UPDATE', 'Department updated'), ('DEPARTMENT_DEACTIVATE', 'Department deactivated'), ('POSITION_CREATE', 'Position created'), ('POSITION_UPDATE', 'Position updated'), ('POSITION_DEACTIVATE', 'Position deactivated'), ('COMPANY_CREATE', 'Company created'), ('COMPANY_UPDATE', 'Company updated'), ('HEADSHIP_ASSIGN', 'Department head appointed'), ('HEADSHIP_END', 'Department headship ended'), ('JOB_GRADE_CREATE', 'Job grade created'), ('JOB_GRADE_UPDATE', 'Job grade updated'), ('EMPLOYEE_CREATE', 'Employee created'), ('EMPLOYEE_UPDATE', 'Employee updated'), ('EMPLOYEE_VIEW_SENSITIVE', 'Sensitive employee data viewed'), ('CONTRACT_CREATE', 'Contract created'), ('CONTRACT_UPDATE', 'Contract updated'), ('CONTRACT_TERMINATE', 'Contract terminated'), ('SALARY_CHANGE', 'Salary changed'), ('SALARY_VIEW', 'Salary history viewed'), ('ASSIGNMENT_CREATE', 'Assignment created'), ('ASSIGNMENT_END', 'Assignment ended'), ('LEAVE_SUBMIT', 'Leave request submitted'), ('LEAVE_APPROVE', 'Leave request approved'), ('LEAVE_REJECT', 'Leave request rejected'), ('LEAVE_CANCEL', 'Leave request cancelled'), ('ATTENDANCE_ADJUST', 'Attendance adjusted'), ('DOCUMENT_UPLOAD', 'Document uploaded'), ('DOCUMENT_DOWNLOAD', 'Document downloaded'), ('DOCUMENT_DELETE', 'Document deleted'), ('PAYROLL_RUN_EXECUTE', 'Payroll run executed'), ('PAYROLL_RUN_APPROVE', 'Payroll run approved'), ('EXPORT_DATA', 'Data exported')], max_length=40, verbose_name='action'),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET_REQUEST', 'PASSWORD_RESET_COMPLETE', 'EMAIL_VERIFIED', 'USER_CREATE', 'USER_DEACTIVATE', 'ACTIVATION_CODE_ISSUE', 'ACTIVATION_CODE_REDEEM', 'ACTIVATION_CODE_FAILED', 'ACTIVATION_CODE_REVOKE', 'ROLE_CHANGE', 'PERMISSION_CHANGE', 'PERMISSION_DENIED', 'DEPARTMENT_CREATE', 'DEPARTMENT_UPDATE', 'DEPARTMENT_DEACTIVATE', 'POSITION_CREATE', 'POSITION_UPDATE', 'POSITION_DEACTIVATE', 'COMPANY_CREATE', 'COMPANY_UPDATE', 'HEADSHIP_ASSIGN', 'HEADSHIP_END', 'JOB_GRADE_CREATE', 'JOB_GRADE_UPDATE', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_VIEW_SENSITIVE', 'CONTRACT_CREATE', 'CONTRACT_UPDATE', 'CONTRACT_TERMINATE', 'SALARY_CHANGE', 'SALARY_VIEW', 'ASSIGNMENT_CREATE', 'ASSIGNMENT_END', 'LEAVE_SUBMIT', 'LEAVE_APPROVE', 'LEAVE_REJECT', 'LEAVE_CANCEL', 'ATTENDANCE_ADJUST', 'DOCUMENT_UPLOAD', 'DOCUMENT_DOWNLOAD', 'DOCUMENT_DELETE', 'PAYROLL_RUN_EXECUTE', 'PAYROLL_RUN_APPROVE', 'EXPORT_DATA'])), name='audit_action_valid'),
        ),
    ]
