# Generated by Django 6.1.1 on 2026-09-12 01:54

import apps.core.validators
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_name', models.CharField(max_length=60, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=60, verbose_name='middle name')),
                ('last_name', models.CharField(max_length=60, verbose_name='last name')),
                ('second_last_name', models.CharField(blank=True, help_text='Common in Spanish-speaking naming conventions.', max_length=60, verbose_name='second last name')),
                ('birth_date', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male'), ('OTHER', 'Other'), ('UNDISCLOSED', 'Prefer not to say')], default='UNDISCLOSED', max_length=20, verbose_name='gender')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('PARTNERED', 'Domestic partnership'), ('UNDISCLOSED', 'Prefer not to say')], default='UNDISCLOSED', max_length=20, verbose_name='marital status')),
                ('nationality', models.CharField(default='GT', help_text='ISO 3166-1 alpha-2 code.', max_length=2, validators=[apps.core.validators.validate_country_code], verbose_name='nationality')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ('last_name', 'second_last_name', 'first_name'),
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='person_name_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('birth_date__gte', datetime.date(1900, 1, 1))), name='person_birth_date_is_plausible', violation_error_message='The date of birth is not plausible.'), models.CheckConstraint(condition=models.Q(('gender__in', ['FEMALE', 'MALE', 'OTHER', 'UNDISCLOSED'])), name='person_gender_valid'), models.CheckConstraint(condition=models.Q(('marital_status__in', ['SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'PARTNERED', 'UNDISCLOSED'])), name='person_marital_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Used in URLs. It does not replace authorization.', unique=True, verbose_name='public ID')),
                ('employee_code', models.CharField(help_text='Never reused after a termination.', max_length=20, unique=True, verbose_name='employee code')),
                ('hire_date', models.DateField(verbose_name='hire date')),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20, verbose_name='employment status')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='termination date')),
                ('user', models.OneToOneField(blank=True, help_text='Empty when the employee has no access to the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='account')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='employees.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ('employee_code',),
                'permissions': [('view_sensitive_pii', 'Can view sensitive personal data')],
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('contact_type', models.CharField(choices=[('MOBILE', 'Mobile phone'), ('LANDLINE', 'Landline'), ('PERSONAL_EMAIL', 'Personal email'), ('WORK_EMAIL', 'Work email')], max_length=20, verbose_name='type')),
                ('value', models.CharField(max_length=150, verbose_name='value')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notes')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='employees.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'contact method',
                'verbose_name_plural': 'contact methods',
                'ordering': ('contact_type', '-is_primary'),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('address_type', models.CharField(choices=[('HOME', 'Home'), ('MAILING', 'Mailing')], default='HOME', max_length=20, verbose_name='type')),
                ('line1', models.CharField(max_length=200, verbose_name='address line 1')),
                ('line2', models.CharField(blank=True, max_length=200, verbose_name='address line 2')),
                ('locality', models.CharField(max_length=100, verbose_name='locality')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('country', models.CharField(default='GT', max_length=2, validators=[apps.core.validators.validate_country_code], verbose_name='country')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employees.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ('-is_primary', 'address_type'),
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse or partner'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('SIBLING', 'Sibling'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], max_length=30, verbose_name='relationship')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('alternate_phone', models.CharField(blank=True, max_length=30, verbose_name='alternate phone')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='1 means the first person to call.', verbose_name='priority')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employees.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'emergency contact',
                'verbose_name_plural': 'emergency contacts',
                'ordering': ('priority',),
                'constraints': [models.UniqueConstraint(fields=('employee', 'priority'), name='uniq_emergency_contact_priority', violation_error_message='That priority is already assigned.'), models.CheckConstraint(condition=models.Q(('priority__gte', 1)), name='emergency_contact_priority_positive'), models.CheckConstraint(condition=models.Q(('relationship__in', ['SPOUSE', 'PARENT', 'CHILD', 'SIBLING', 'FRIEND', 'OTHER'])), name='emergency_contact_relationship_valid')],
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('document_type', models.CharField(choices=[('DPI', 'National ID (DPI/CUI)'), ('NIT', 'Tax ID (NIT)'), ('IGSS', 'Social security number (IGSS)'), ('PASSPORT', 'Passport'), ('DRIVER_LICENSE', "Driver's license")], max_length=20, verbose_name='document type')),
                ('number', models.CharField(help_text='Stored without spaces or dashes.', max_length=40, verbose_name='number')),
                ('issuing_country', models.CharField(default='GT', max_length=2, validators=[apps.core.validators.validate_country_code], verbose_name='issuing country')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='issued on')),
                ('expires_on', models.DateField(blank=True, help_text='Empty means it does not expire.', null=True, verbose_name='expires on')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary identification')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='employees.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'identity document',
                'verbose_name_plural': 'identity documents',
                'ordering': ('document_type',),
                'constraints': [models.UniqueConstraint(fields=('document_type', 'number', 'issuing_country'), name='uniq_identity_document', violation_error_message='That document is already registered.'), models.UniqueConstraint(condition=models.Q(('expires_on__isnull', True)), fields=('person', 'document_type', 'issuing_country'), name='uniq_permanent_document_per_person', violation_error_message='That person already has a permanent document of this type.'), models.CheckConstraint(condition=models.Q(('issued_on__isnull', True), ('expires_on__isnull', True), ('expires_on__gte', models.F('issued_on')), _connector='OR'), name='identity_document_dates_ordered', violation_error_message='The expiry date cannot precede the issue date.'), models.CheckConstraint(condition=models.Q(('document_type__in', ['DPI', 'NIT', 'IGSS', 'PASSPORT', 'DRIVER_LICENSE'])), name='identity_document_type_valid')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_status'], name='employee_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('termination_date__isnull', True), ('termination_date__gte', models.F('hire_date')), _connector='OR'), name='employee_termination_after_hire', violation_error_message='The termination date cannot precede the hire date.'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('employment_status', 'TERMINATED'), ('termination_date__isnull', False)), models.Q(models.Q(('employment_status', 'TERMINATED'), _negated=True), ('termination_date__isnull', True)), _connector='OR'), name='employee_termination_is_consistent', violation_error_message='A terminated employee needs a termination date, and only a terminated one.'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employment_status__in', ['ACTIVE', 'ON_LEAVE', 'SUSPENDED', 'TERMINATED'])), name='employee_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(fields=('person', 'contact_type', 'value'), name='uniq_contact_method', violation_error_message='That contact detail is already registered.'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person', 'contact_type'), name='uniq_primary_contact_per_type', violation_error_message='There is already a primary contact of this type.'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.CheckConstraint(condition=models.Q(('contact_type__in', ['MOBILE', 'LANDLINE', 'PERSONAL_EMAIL', 'WORK_EMAIL'])), name='contact_method_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('person',), name='uniq_primary_address_per_person', violation_error_message='That person already has a primary address.'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.CheckConstraint(condition=models.Q(('address_type__in', ['HOME', 'MAILING'])), name='address_type_valid'),
        ),
    ]
